"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3, Download, Eye, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import type { ContractorQuote, ProjectSpec, QuoteRecommendation, SiteContext } from "@/types";
import { SitePlan } from "./site-plan";
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);

export function QuoteComparison({ project, site, quotes, recommendation, onBack, onDownload }: { project: ProjectSpec; site: SiteContext; quotes: ContractorQuote[]; recommendation: QuoteRecommendation; onBack: () => void; onDownload: () => void }) {
  const [normalized, setNormalized] = useState(false);
  const [selected, setSelected] = useState("quote-c");
  const selectedQuote = quotes.find(q => q.id === selected) || quotes[0];
  const selectedResult = recommendation.quotes.find(q => q.quoteId === selectedQuote.id)!;
  const affectedScope = selectedResult.adjustments.map(a => a.scopeItemId);
  const affectedElements = project.scopeItems.filter(s => affectedScope.includes(s.id)).flatMap(s => s.elementId ? [s.elementId] : []);
  const max = Math.max(...recommendation.quotes.map(q => q.normalizedTotal));
  const cheapestHeadline = [...quotes].sort((a, b) => a.headlineTotal - b.headlineTotal)[0];
  const cheapestResult = recommendation.quotes.find(q => q.quoteId === cheapestHeadline.id)!;
  const winner = recommendation.quotes.find(q => q.quoteId === recommendation.recommendedQuoteId)!;

  return <section className="quote-comparison">
    <div className="quote-controls"><button className="text-button back-button" onClick={onBack}><ArrowLeft size={14}/>Back to your design</button><div className="price-switch"><button className={!normalized ? "selected" : ""} onClick={() => setNormalized(false)}>Headline prices</button><button className={normalized ? "selected" : ""} onClick={() => setNormalized(true)}><Sparkles size={13}/>Compare complete scope</button></div><span className="quote-version">PROJECT REVISION {project.version} · SYNTHETIC BIDS</span></div>
    <div className={`comparison-banner ${normalized ? "revealed" : ""}`} aria-live="polite"><div className="banner-symbol">{normalized ? <ShieldCheck size={24}/> : <Eye size={24}/>}</div><div><p className="eyebrow">{normalized ? "THE SAME PROJECT. THE TRUE COMPARISON." : "THREE PRICES. THREE DIFFERENT PROMISES."}</p><h2>{normalized ? `The “cheapest” bid leaves ${money(cheapestResult.normalizedTotal - cheapestResult.headlineTotal)} outside the price.` : `A ${money(cheapestHeadline.headlineTotal)} bid looks like the obvious choice.`}</h2><p>{normalized ? recommendation.explanation : "But does it include the whole project? Compare each bid against the scope you just designed."}</p></div>{!normalized && <button className="button primary" onClick={() => setNormalized(true)}>Reveal the complete cost<ArrowRight size={16}/></button>}</div>
    <div className="quote-grid">{quotes.map((quote, index) => {
      const result = recommendation.quotes.find(q => q.quoteId === quote.id)!;
      const recommended = normalized && quote.id === recommendation.recommendedQuoteId;
      const addition = result.normalizedTotal - quote.headlineTotal;
      return <article className={`quote-card ${recommended ? "best" : ""} ${normalized && addition > 0 ? "has-gap" : ""}`} key={quote.id}>
        <div className="contractor-head"><span className="contractor-avatar">{String.fromCharCode(65+index)}</span><div><h3>{quote.contractorName}</h3><span>FICTIONAL CONTRACTOR · BID {String.fromCharCode(65+index)}</span></div>{recommended && <Check size={17}/>}</div>
        <div className="quote-badge">{recommended ? <span className="best-badge"><Sparkles size={10}/>Recommended for your project</span> : !normalized && quote.id === cheapestHeadline.id ? <span className="neutral-badge">Lowest headline price</span> : <span className="neutral-badge">{index === 1 ? "Fastest timeline" : normalized ? "Scope adjustment required" : "Complete stated scope"}</span>}</div>
        <p className="price-caption">{normalized ? "NORMALIZED PROJECT COST" : "HEADLINE QUOTE"}</p><div className="quote-price">{money(normalized ? result.normalizedTotal : quote.headlineTotal)}</div>
        <div className="quote-bar"><span className="base-bar" style={{ width: `${quote.headlineTotal / max * 100}%` }}/><span className="gap-bar" style={{ width: normalized ? `${addition / max * 100}%` : 0 }}/></div>
        <p className={`adjustment-caption ${normalized && addition ? "gap" : ""}`}>{normalized ? addition ? `${money(quote.headlineTotal)} headline + ${money(addition)} scope adjustment` : "Every required line item accounted for." : "Quoted total before checking scope differences."}</p>
        {normalized && <div className="adjustment-list">{result.adjustments.length ? result.adjustments.map(a => <div key={a.scopeItemId}><span>{a.kind === "allowance" ? "Allowance gap" : "Excluded"}: {project.scopeItems.find(s => s.id === a.scopeItemId)?.description}</span><strong>+{money(a.amount)}</strong></div>) : <div className="no-gaps"><ShieldCheck size={14}/>No exclusions or allowance gaps detected</div>}</div>}
        <div className="contractor-terms"><span><Clock3 size={13}/>{quote.timelineWeeks} weeks</span><span><ShieldCheck size={13}/>{quote.warrantyYears}-year warranty</span></div>
        {normalized && <p className="bid-rationale">{result.rationale}</p>}
        <button className={`xray-button ${selected === quote.id ? "selected" : ""}`} onClick={() => { setSelected(quote.id); setNormalized(true); }}><Eye size={13}/>Inspect this bid’s scope<ArrowRight size={13}/></button>
      </article>;
    })}</div>
    {normalized && <>
    <section className="scope-xray"><div className="xray-visual"><div className="xray-label"><Eye size={14}/>SCOPE X-RAY<span>{affectedElements.length ? "Highlighted work needs clarification" : "Complete stated scope"}</span></div><SitePlan project={project} site={site} highlighted={affectedElements} compact/></div><div className="xray-detail"><p className="eyebrow">YOUR DESIGN IS THE REFERENCE</p><h2>{selectedQuote.contractorName}</h2><p className="xray-description">{affectedElements.length ? "The highlighted part of your project is not fully priced in this bid. These adjustments come directly from your agreed scope." : "This bid includes all the required scope in your design. There is no omitted component or allowance shortfall to add."}</p>{selectedResult.adjustments.map(a => <div className="xray-gap" key={a.scopeItemId}><TriangleAlert size={16}/><div><h3>{project.scopeItems.find(s => s.id === a.scopeItemId)?.description}</h3><p>{a.kind === "allowance" ? "The bid includes a provisional allowance below the scope estimate." : "Excluded from the contractor’s headline; still required to complete your project."}</p></div><strong>{money(a.amount)}</strong></div>)}<div className="xray-total"><span>{money(selectedQuote.headlineTotal)} headline</span><ArrowRight size={17}/><strong>{money(selectedResult.normalizedTotal)} complete scope</strong></div><p className="uncertainty-note">{selectedResult.uncertainty}</p></div></section>
    <section className="scope-table-section"><div className="section-heading"><h2>Every detail, on the same page.</h2><button className="button secondary" onClick={onDownload}><Download size={13}/>Download bid package</button></div><div className="scope-table-wrap"><table className="scope-table"><thead><tr><th>YOUR PROJECT SCOPE</th>{quotes.map(q => <th key={q.id}>{q.contractorName}</th>)}</tr></thead><tbody>{project.scopeItems.filter(s => s.required).map(scope => <tr key={scope.id}><td>{scope.description}<small>Planning estimate {money(scope.estimatedCost)}</small></td>{quotes.map(q => { const line = q.lineItems.find(l => l.scopeItemId === scope.id); return <td key={q.id} className={!line || line.status === "excluded" ? "excluded-cell" : line.status === "allowance" ? "allowance-cell" : "included-cell"}>{!line ? "Missing" : line.status === "excluded" ? "Excluded" : line.status === "allowance" ? `${money(line.amount)} allowance` : <><Check size={12}/>{money(line.amount)}</>}</td>; })}</tr>)}<tr className="scope-total"><td>Normalized total</td>{quotes.map(q => <td key={q.id}>{money(recommendation.quotes.find(n => n.quoteId === q.id)!.normalizedTotal)}</td>)}</tr></tbody></table></div></section>
    <section className="recommendation-footer"><div><p className="eyebrow">BEFORE YOU CHOOSE</p><h2>A better conversation with your contractor.</h2><ul>{recommendation.negotiationQuestions.map(q => <li key={q}>{q}</li>)}</ul></div><div className="value-card"><ShieldCheck size={22}/><p>Recommended complete scope</p><strong>{money(winner.normalizedTotal)}</strong><span>{winner.contractorName}</span><small>{winner.normalizedTotal <= project.budgetMaximum ? `${money(project.budgetMaximum - winner.normalizedTotal)} below your spending limit` : `${money(winner.normalizedTotal - project.budgetMaximum)} above your spending limit`}</small></div></section>
    <details className="provenance"><summary><span>Payment terms and comparison methodology</span><span>View details</span></summary>{quotes.map(q => <p key={q.id}><strong>{q.contractorName}:</strong> {q.paymentTerms}</p>)}<p>Normalized total = headline + ProjectSpec estimates for required missing/excluded scope + max(0, scope estimate − included allowance). No allowance is counted twice. Ranks reflect normalized price; Astra’s recommendation also considers schedule, warranty, and completeness. These are synthetic bids and planning estimates, not offers or guaranteed final costs.</p></details>
    </>}
  </section>;
}
